name: ost-trigger
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
      
jobs:
  trigger-ost:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.review.state == 'approved' }}
    timeout-minutes: 5 # should get enqueued in 1m
    steps:
      - name: trigger
        env:
          OST_LISTEN_PORT: ${{ secrets.OST_LISTEN_PORT }}
        run: |
          cd /var/lib/nginx/gh
          echo ${{ github.event.workflow_run.artifacts_url }} | runuser -u nginx tee queue
          nc -l -I 256 -W 1 ${OST_LISTEN_PORT} | grep '^run$'
          mv -f queue run
          nc -l -I 256 -W 1 ${OST_LISTEN_PORT} | grep '^rm$'
          rm -f run
          nc -l -I 256 -W 1 ${OST_LISTEN_PORT} | grep '^done$'
